tap 'homebrew/binary'
tap 'homebrew/completions'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'caskroom/cask'
tap 'neovim/neovim'

brew 'ack'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'axel'
brew 'bash'
brew 'bash-completion'
brew 'bison'
brew 'brew-cask-completion'
brew 'ccat'
brew 'colordiff'
brew 'curl'
brew 'devd'
brew 'diff-so-fancy'
brew 'direnv'
brew 'findutils', args: ['--with-default-names']
brew 'gdbm'
brew 'gist'
brew 'git'
brew 'git-flow'
brew 'gnu-sed', args: ['--with-default-names']
# Disabled.
# brew 'gnupg'
brew 'gnupg2'
brew 'go'
brew 'graphviz'
brew 'grep', args: ['--with-default-names']
brew 'htop-osx'
brew 'httpie'
brew 'ipcalc'
brew 'jq'
brew 'lftp'
brew 'libmagic'
brew 'libpng'
brew 'libtool'
brew 'makedepend'
brew 'mercurial'
brew 'mtr'
brew 'neovim'
brew 'ngrep'
brew 'nmap'
brew 'oniguruma'
brew 'openssl'
brew 'packer'
brew 'packer-completion'
brew 'pcre'
brew 'peco'
brew 'pkg-config'
brew 'python'
brew 'rbenv'
brew 'rbenv-default-gems'
# No longer available.
# brew 'rbenv-gem-rehash'
brew 'rbenv-gemset'
brew 'readline'
brew 'rename'
brew 'rsync'
brew 'ruby-build'
brew 's-search'
brew 'socat'
brew 'sqlite'
brew 'terraform'
brew 'tig'
brew 'tree'
brew 'unrar'
# Disabled.
# brew 'v8-315'
brew 'vagrant-completion'
brew 'vim', args: ['--override-system-vi']
brew 'watch'
brew 'watchman'
brew 'wget'
brew 'whatmask'
brew 'xz'
